development:
  adapter: postgresql
  database: arielisaacs
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password: